version: '3'

services: 
    anken_server:
        image: python:3
        container_name: anken_server
        working_dir: /src
        environment:
            - http_proxy=${http_proxy}
            - https_proxy=${https_proxy}
            - HTTP_PROXY=${HTTP_PROXY}
            - HTTPS_PROXY=${HTTPS_PROXY}
        volumes:
            - C:\Users\Tetsushi\Documents\Source\AnkenSugoroku\docker\runtime\src:/src/
            - C:\Users\Tetsushi\Documents\Source\AnkenSugoroku\src\dist\project-board-game\assets:/assets/
        command: ["bash", "startup.sh"]

    rproxy:
        depends_on: 
            - anken_server
        image: nginx:latest
        container_name: reverse_proxy
        volumes: 
            - C:\Users\Tetsushi\Documents\Source\AnkenSugoroku\docker\runtime\reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf
            - C:\Users\Tetsushi\Documents\Source\AnkenSugoroku\docker\runtime\nginx.conf:/etc/nginx/nginx.conf
            - C:\Users\Tetsushi\Documents\Source\AnkenSugoroku\src\dist\project-board-game:/sugoroku/
        ports: 
            - "8080:8080"
