version: '3'

services: 
    anken_server:
        image: python:3
        container_name: anken_server
        working_dir: /src
        environment:
            - http_proxy=${http_proxy}
            - https_proxy=${https_proxy}
            - HTTP_PROXY=${HTTP_PROXY}
            - HTTPS_PROXY=${HTTPS_PROXY}
        volumes:
            - ./src:/src/
            # for using docker on WSL2. path must be Absolute path
            # - C:\path\to\repo\AnkenSugoroku\docker\runtime\src:/src/
        command: ["bash", "startup.sh"]

    rproxy:
        depends_on: 
            - anken_server
        image: nginx:latest
        container_name: reverse_proxy
        volumes: 
            - reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf
            - ../../src/dist/project-board-game:/sugoroku/
            # for using docker on WSL2. path must be Absolute path
            # - C:\path\to\repo\AnkenSugoroku\docker\runtime\reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf
            # - C:\path\to\repo\AnkenSugoroku\docker\runtime\reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf
        ports: 
            - "8080:8080"

